version: '3'

services:
  node_server:
    build: src/.
    # build from Dockerfile
    ports:
     - "3000:3000"
    volumes:
     - :/src
    depends_on: 
     - mysql
     - reddis
  # redis:
  #   image: redis
  mysql:
    image: mysql:8.0
    env_file: ./env
    environment: 
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - :/app/sql

