version: '3'

services:
  node_server:
    build: .
    # build from Dockerfile
    ports:
     - "4000:4000"
    volumes:
     - ./_data:/var/lib/app
     - ./nodemon.json:/app/nodemon.json
    depends_on: 
     - mysql
    #  - reddis
  # redis:
  #   image: redis
  mysql:
    image: mysql:8.0
    env_file: .env
    ports:
      - "33061:3306"
    environment: 
      - MYSQL_DATABASE:$MYSQL_DATABASE
      - MYSQL_USER:$MYSQL_USER
      - MYSQL_PASSWORD:$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD:$MYSQL_ROOT_PASSWORD
    volumes:
      - ./_data:/var/lib/mysql

